#ASSIGNMENT=wp1p1
#ASSIGNMENT=wp1
#ASSIGNMENT=wp2
#ASSIGNMENT=wp3
ASSIGNMENT=project
TEAM_MEMBERS_CSV="Yinquan Hao 107989208; Lie Han 110898739"
# list space-separated completed components: cooperative preemptive signals swap filesystem network multicore
PROJECT_PARTS=cooperative signals
PROJECT_POINTS=50
